# Generated by Django 4.0.3 on 2022-03-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guns_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gun',
            name='caliber',
            field=models.CharField(max_length=5),
        ),
    ]
